name = "KAT Notebook"
prefix = "KNB"
author = "Katalam"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "book.paa",
    "clientsideonly.txt",
]

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
]

parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
]
